name: Update GitHub Stats in README

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@v1
        with:
          username: abdullhss
          token: ${{ secrets.GH_TOKEN }}
          hide_border: true
          show_icons: true
          include_all_commits: true
          count_private: true
          theme: react
          bg_color: 0D1117
          title_color: 00D8FF
          icon_color: 00D8FF
          text_color: ffffff
          output: stats/github-stats.svg

      - name: Generate Top Languages
        uses: anuraghazra/github-readme-stats@v1
        with:
          username: abdullhss
          token: ${{ secrets.GH_TOKEN }}
          hide_border: true
          theme: react
          bg_color: 0D1117
          title_color: 00D8FF
          text_color: ffffff
          layout: compact
          output: stats/top-langs.svg

      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add stats/
          git diff --quiet && git diff --staged --quiet || (git commit -m "♻️ Update GitHub stats" && git push)
