name: Update README with Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats Card
        uses: anuraghazra/github-readme-stats@v1
        with:
          username: abdullhss
          token: ${{ secrets.GH_TOKEN }}
          hide_border: true
          show_icons: true
          include_all_commits: true
          count_private: true
