name: Update GitHub Stats in README

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create stats directory
        run: mkdir -p stats

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@v1
        with:
          username: abdullhss
          token: ${{ secrets.GH_TOKEN }}
          hide_border: true
          show_icons: true
          include_all_commits: true
          count_private: true
          theme: react
          bg_color: 0D1117
          title_color: 00D8FF
          icon_color: 00D8FF
          text_color: ffffff
          output: stats/github-stats.svg

      - name: Generate Top Languages
        uses: anuraghazra/github-readme-stats@v1
        with:
          username: abdullhss
          token: ${{ secrets.GH_TOKEN }}
          hide_border: true
          theme: react
          bg_color: 0D1117
          title_color: 00D8FF
          text_color: ffffff
          layout: compact
          output: stats/top-langs.svg

      - name: Check if files were generated
        run: |
          echo "Checking generated files..."
          ls -la stats/
          if [ ! -f "stats/github-stats.svg" ]; then
            echo "Error: github-stats.svg was not generated"
            exit 1
          fi
          if [ ! -f "stats/top-langs.svg" ]; then
            echo "Error: top-langs.svg was not generated"
            exit 1
          fi
          echo "All files generated successfully!"

      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add stats/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "♻️ Update GitHub stats"
            git push
            echo "Changes committed and pushed successfully!"
          fi
